# Экзаменационное задание

Суть проекта — отследить влияние условий жизни учащихся в возрасте от 15 до 22 лет на их успеваемость по математике, чтобы на ранней стадии выявлять талантливых студентов и находящихся в группе риска.

Сделать это можно с помощью модели, которая предсказывала бы результаты госэкзамена по математике для каждого ученика школы. Чтобы определиться с параметрами будущей модели, проведите разведывательный анализ данных и составьте отчет по его результатам.

Ниже вы найдете пошаговую инструкцию по выполнению проекта. Будьте внимательны к условиям: какие значения необходимо вывести на экран, где нужно построить графики и написать текстовые выводы в отдельных MarkDown-ячейках.

**Разбалловка за каждую часть:**
| Часть | Баллы |
|--------|--------|
| Часть 1 | 15 |
| Часть 2 | 25 |
| Часть 3 | 25 |
| Часть 4 | 25 |
| Часть 5 | 10 |

## Описание данных


| Название колонки | Описание                                                                                                                                |
| ---------------- | --------------------------------------------------------------------------------------------------------------------------------------- |
| **absences**     | Количество пропущенных занятий                                                                                                          |
| **address**      | Тип адреса ученика ('U' — городской, 'R' — за городом)                                                                                  |
| **age**          | Возраст ученика (от 15 до 22 лет)                                                                                                       |
| **activities**   | Дополнительные внеучебные занятия (yes / no)                                                                                            |
| **Fedu**         | Образование отца (0 — нет, 1 — 4 класса, 2 — 5–9 классы, 3 — среднее специальное/11 классов, 4 — высшее)                                |
| **Fjob**         | Работа отца ('teacher' — учитель, 'health' — здравоохранение, 'services' — госслужба, 'at_home' — не работает, 'other' — другое)        |
| **famrel**       | Семейные отношения (от 1 — очень плохо до 5 — очень хорошо)                                                                             |
| **famsize**      | Размер семьи ('LE3' — ≤3 человека, 'GT3' — >3 человек)                                                                                  |
| **famsup**       | Семейная образовательная поддержка (yes / no)                                                                                           |
| **failures**     | Количество внеучебных неудач (n, если 1≤n≤3, иначе 0)                                                                                   |
| **free time**    | Свободное время после школы (от 1 — очень мало до 5 — очень много)                                                                      |
| **goout**        | Проведение времени с друзьями (от 1 — очень мало до 5 — очень много)                                                                    |
| **guardian**     | Опекун ('mother' — мать, 'father' — отец, 'other' — другое)                                                                             |
| **health**       | Текущее состояние здоровья (от 1 — очень плохо до 5 — очень хорошо)                                                                     |
| **higher**       | Хочет получить высшее образование (yes / no)                                                                                            |
| **internet**     | Наличие интернета дома (yes / no)                                                                                                       |
| **Medu**         | Образование матери (0 — нет, 1 — 4 класса, 2 — 5–9 классы, 3 — среднее специальное/11 классов, 4 — высшее)                              |
| **Mjob**         | Работа матери ('teacher' — учитель, 'health' — здравоохранение, 'services' — госслужба, 'at_home' — не работает, 'other' — другое)      |
| **nursery**      | Посещал детский сад (yes / no)                                                                                                          |
| **paid**         | Дополнительные платные занятия по математике (yes / no)                                                                                 |                                                                   |
| **Pstatus**      | Статус совместного проживания родителей ('T' — вместе, 'A' — раздельно)                                                                 |
| **reason**       | Причина выбора школы ('home' — близость к дому, 'reputation' — репутация школы, 'course' — образовательная программа, 'other' — другое) |
| **romantic**     | В романтических отношениях (yes / no)                                                                                                   |
| **school**       | Аббревиатура школы, в которой учится ученик                                                                                             |
| **schoolsup**    | Дополнительная образовательная поддержка (yes / no)                                                                                     |
| **score**        | Баллы по госэкзамену по математике                                                                                                      |
| **sex**          | Пол ученика ('F' — женский, 'M' — мужской)                                                                                              |
| **studytime**    | Время на учебу помимо школы в неделю (1 — <2 часов, 2 — 2–5 часов, 3 — 5–10 часов, 4 — >10 часов)                                       |
| **traveltime**   | Время в пути до школы (1 — <15 мин., 2 — 15–30 мин., 3 — 30–60 мин., 4 — >60 мин.)                                                      |

In [1]:
# Ячейка с импортами, дополняйте по своему желанию
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import scipy.stats as sm

pd.set_option('display.max_rows', 50)  # Показывать больше строк
pd.set_option('display.max_columns', 50)  # Показывать больше колонок
pd.options.display.float_format = '{:,.2f}'.format

## Часть 1. Первичное исследование данных

Первым делом познакомьтесь с данными и посмотрите на наличие в них моментов, подлежащих очистке:
- пропуски,
- выбросы,
- дубликаты,
- ошибочные или странные значения,
- количество уникальных значений для номинативных переменных.

Запишите результаты наблюдений в небольшом выводе в конце. Это станет стартовой точкой для более глубокого анализа в следующих частях проекта.

In [2]:
data = pd.read_csv('stud_math.csv')
# Размеры и общий вид датасета
print(f'Количество строк в датасете: {data.shape[0]}')
print(f'Количество столбцов в датасете: {data.shape[1]}')
display(data.head(10))

Количество строк в датасете: 395
Количество столбцов в датасете: 30

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,"studytime, granular",higher,internet,romantic,famrel,freetime,goout,health,absences,score
0,GP,F,18,U,NaN,A,4.00,4.00,at_home,teacher,course,mother,2.00,2.00,0.00,yes,no,no,no,yes,-6.00,yes,NaN,no,4.00,3.00,4.00,3.00,6.00,30.00
1,GP,F,17,U,GT3,NaN,1.00,1.00,at_home,other,course,father,1.00,2.00,0.00,no,yes,no,no,no,-6.00,yes,yes,no,5.00,3.00,3.00,3.00,4.00,30.00
2,GP,F,15,U,LE3,T,1.00,1.00,at_home,other,other,mother,1.00,2.00,3.00,yes,no,NaN,no,yes,-6.00,yes,yes,NaN,4.00,3.00,2.00,3.00,10.00,50.00
3,GP,F,15,U,GT3,T,4.00,2.00,health,NaN,home,mother,1.00,3.00,0.00,no,yes,yes,yes,yes,-9.00,yes,yes,yes,3.00,2.00,2.00,5.00,2.00,75.00
4,GP,F,16,U,GT3,T,3.00,3.00,other,other,home,father,1.00,2.00,0.00,no,yes,yes,no,yes,-6.00,yes,no,no,4.00,3.00,2.00,5.00,4.00,50.00
5,GP,M,16,U,LE3,T,4.00,3.00,services,other,reputation,mother,1.00,2.00,0.00,no,yes,yes,yes,yes,-6.00,yes,yes,no,5.00,4.00,2.00,5.00,10.00,75.00
6,GP,M,16,NaN,LE3,T,2.00,2.00,other,other,home,mother,1.00,2.00,0.00,no,no,no,no,yes,-6.00,yes,yes,no,4.00,4.00,4.00,3.00,0.00,55.00
7,GP,F,17,U,GT3,A,4.00,4.00,other,teacher,home,mother,2.00,2.00,0.00,yes,yes,no,no,yes,-6.00,yes,no,no,4.00,1.00,4.00,1.00,6.00,30.00
8,GP,M,15,U,LE3,A,3.00,2.00,services,other,home,mother,1.00,2.00,0.00,no,yes,yes,no,yes,-6.00,yes,yes,no,NaN,2.00,2.00,1.00,0.00,95.00
9,GP,M,15,U,NaN,NaN,3.00,4.00,other,other,home,mother,1.00,2.00,0.00,no,yes,yes,yes,yes,-6.00,yes,yes,no,5.00,5.00,1.00,5.00,0.00,75.00

In [3]:
# Типы данных столбцов датасета
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 30 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   school               395 non-null    object
 1   sex                  395 non-null    object
 2   age                  395 non-null    int64
 3   address              378 non-null    object
 4   famsize              368 non-null    object
 5   Pstatus              350 non-null    object
 6   Medu                 392 non-null    float64
 7   Fedu                 371 non-null    float64
 8   Mjob                 376 non-null    object
 9   Fjob                 359 non-null    object
 10  reason               378 non-null    object
 11  guardian             364 non-null    object
 12  traveltime           367 non-null    float64
 13  studytime            388 non-null    float64
 14  failures             373 non-null    float64
 15  schoolsup            386 non-null    object
 16  famsup               356 non-null    object
 17  paid                 355 non-null    object
 18  activities           381 non-null    object
 19  nursery              379 non-null    object
 20  studytime, granular  388 non-null    float64
 21  higher               375 non-null    object
 22  internet             361 non-null    object
 23  romantic             364 non-null    object
 24  famrel               368 non-null    float64
 25  freetime             384 non-null    float64
 26  goout                387 non-null    float64
 27  health               380 non-null    float64
 28  absences             383 non-null    float64
 29  score                389 non-null    float64
dtypes: float64(12), int64(1), object(17)
memory usage: 92.7+ KB

In [4]:
# Определение столбцов с пропусками
print('Количество пропусков по столбцам:')
data.isna().sum()

Количество пропусков по столбцам:

school                  0
sex                     0
age                     0
address                17
famsize                27
Pstatus                45
Medu                    3
Fedu                   24
Mjob                   19
Fjob                   36
reason                 17
guardian               31
traveltime             28
studytime               7
failures               22
schoolsup               9
famsup                 39
paid                   40
activities             14
nursery                16
studytime, granular     7
higher                 20
internet               34
romantic               31
famrel                 27
freetime               11
goout                   8
health                 15
absences               12
score                   6
dtype: int64

In [5]:
# Получение описательных статистик для определения выбросов
# у количественных переменных
display(data.describe())

,age,Medu,Fedu,traveltime,studytime,failures,"studytime, granular",famrel,freetime,goout,health,absences,score
count,395.00,392.00,371.00,367.00,388.00,373.00,388.00,368.00,384.00,387.00,380.00,383.00,389.00
mean,16.70,2.75,2.61,1.44,2.04,0.34,-6.12,3.94,3.23,3.11,3.53,7.28,52.26
std,1.28,1.10,2.23,0.69,0.84,0.74,2.53,0.93,0.99,1.12,1.40,23.47,22.92
min,15.00,0.00,0.00,1.00,1.00,0.00,-12.00,-1.00,1.00,1.00,1.00,0.00,0.00
25%,16.00,2.00,2.00,1.00,1.00,0.00,-6.00,4.00,3.00,2.00,3.00,0.00,40.00
50%,17.00,3.00,2.00,1.00,2.00,0.00,-6.00,4.00,3.00,3.00,4.00,4.00,55.00
75%,18.00,4.00,3.00,2.00,2.00,0.00,-3.00,5.00,4.00,4.00,5.00,8.00,70.00
max,22.00,4.00,40.00,4.00,4.00,3.00,-3.00,5.00,5.00,5.00,5.00,385.00,100.00

In [6]:
print(f'Количество строк-дубликатов: {data.duplicated().sum()}')

Количество строк-дубликатов: 0

In [7]:
# Строки с отрцательным значением переменной "famrel"
#==============================================================================
print(f'Количество аномальных строк: {data[data['famrel'] < 0].shape[0]}')
data[data['famrel'] < 0]

Количество аномальных строк: 1

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,"studytime, granular",higher,internet,romantic,famrel,freetime,goout,health,absences,score
25,GP,F,16,U,GT3,NaN,2.00,2.00,services,services,home,mother,1.00,1.00,2.00,no,yes,yes,no,no,-3.00,yes,yes,no,-1.00,2.00,2.00,5.00,14.00,40.00

In [33]:
# Строки для учеников, у которых школа расположена поблизости к дому,
# а время в пути до школы превышает 60 мин.
print(f'Количество аномальных строк: {data[
    (data['reason'] == 'home') & (data['traveltime'] == 4)
].shape[0]}')
data[(data['reason'] == 'home') & (data['traveltime'] == 4)]

Количество аномальных строк: 2

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,"studytime, granular",higher,internet,romantic,famrel,freetime,goout,health,absences,score
108,GP,M,15,R,GT3,NaN,4.00,4.00,other,other,home,father,4.00,4.00,NaN,no,yes,yes,yes,yes,-12.00,yes,yes,yes,1.00,3.00,5.00,1.00,6.00,65.00
375,MS,F,18,R,GT3,T,1.00,1.00,other,other,home,mother,4.00,3.00,0.00,no,no,no,no,yes,-9.00,yes,yes,no,4.00,3.00,2.00,4.00,2.00,50.00

In [ ]:
#======================================================================
#==============================================================================
data[(data['studytime'] == 1) & (data['activities'] == 'no') & (data['traveltime'] < 3) & (data['freetime'] == 1)]

In [ ]:
data[(data['studytime'] == 4) & (data['freetime'] == 5)]

In [ ]:
print(f'Количество аномальных строк: {data[(data['Fedu'] < 2) & ((data['Fjob'] == 'teacher') | (data['Fjob'] == 'health') | (data['Fjob'] == 'services'))].shape[0]}')
data[(data['Fedu'] < 2) & ((data['Fjob'] == 'teacher') | (data['Fjob'] == 'health') | (data['Fjob'] == 'services'))]

In [ ]:
print(f'Количество аномальных строк: {data[(data['Medu'] < 2) & ((data['Mjob'] == 'teacher') | (data['Mjob'] == 'health') | (data['Mjob'] == 'services'))].shape[0]}')
data[(data['Medu'] < 2) & ((data['Mjob'] == 'teacher') | (data['Mjob'] == 'health') | (data['Mjob'] == 'services'))]

In [34]:
# Строки для учеников, у которых родители проживают совместно,
# но не являются опекунами
print(f'Количество аномальных строк: {data[
    (data['Pstatus'] == 'T') & (data['guardian'] == 'other')
].shape[0]}')
data[(data['Pstatus'] == 'T') & (data['guardian'] == 'other')]

Количество аномальных строк: 20

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,"studytime, granular",higher,internet,romantic,famrel,freetime,goout,health,absences,score
127,GP,F,19,U,GT3,T,0.00,1.00,at_home,other,course,other,1.00,2.00,3.00,no,NaN,no,no,no,-6.00,no,no,no,3.00,4.00,2.00,5.00,2.00,45.00
152,GP,F,15,R,GT3,T,3.00,3.00,services,NaN,reputation,other,2.00,3.00,2.00,no,yes,yes,yes,NaN,-9.00,yes,yes,yes,4.00,2.00,1.00,3.00,8.00,50.00
192,GP,M,17,U,GT3,T,1.00,2.00,at_home,services,other,other,2.00,2.00,0.00,no,no,NaN,yes,no,-6.00,yes,yes,no,4.00,4.00,4.00,5.00,12.00,40.00
244,GP,F,18,U,GT3,T,2.00,1.00,other,other,course,other,2.00,3.00,0.00,no,yes,yes,no,no,-9.00,yes,yes,yes,4.00,4.00,4.00,3.00,0.00,NaN
251,GP,M,16,U,GT3,T,3.00,3.00,at_home,other,reputation,other,3.00,2.00,0.00,yes,yes,no,no,no,-6.00,yes,NaN,no,5.00,3.00,3.00,2.00,6.00,50.00
270,GP,F,19,NaN,GT3,T,3.00,3.00,other,services,home,other,1.00,2.00,2.00,no,yes,yes,yes,yes,-6.00,yes,yes,no,4.00,3.00,5.00,5.00,NaN,NaN
296,GP,F,19,U,GT3,T,4.00,4.00,health,other,reputation,other,2.00,2.00,0.00,no,yes,yes,yes,yes,-6.00,yes,yes,no,2.00,3.00,4.00,2.00,0.00,0.00
297,GP,F,18,U,LE3,T,4.00,3.00,other,other,home,other,2.00,2.00,0.00,no,yes,yes,no,yes,-6.00,yes,yes,yes,4.00,4.00,5.00,2.00,10.00,40.00
304,GP,M,19,U,GT3,T,3.00,3.00,other,other,home,other,1.00,2.00,1.00,no,yes,no,yes,yes,-6.00,yes,yes,yes,4.00,4.00,4.00,3.00,20.00,65.00
305,GP,F,18,U,GT3,T,2.00,4.00,services,at_home,reputation,other,1.00,2.00,1.00,no,yes,NaN,yes,yes,-6.00,yes,yes,no,4.00,4.00,3.00,3.00,8.00,60.00
309,GP,F,19,U,LE3,T,1.00,1.00,at_home,NaN,reputation,other,1.00,2.00,1.00,yes,yes,NaN,yes,no,-6.00,yes,yes,no,NaN,4.00,3.00,3.00,18.00,50.00
310,GP,F,19,U,LE3,T,1.00,NaN,services,services,home,other,NaN,2.00,1.00,no,no,no,yes,no,-6.00,yes,no,yes,4.00,2.00,4.00,3.00,0.00,0.00
311,GP,F,19,U,GT3,T,2.00,1.00,at_home,other,other,other,3.00,2.00,0.00,no,yes,no,no,yes,-6.00,no,yes,yes,3.00,NaN,1.00,2.00,20.00,65.00
312,GP,M,19,U,GT3,T,1.00,2.00,other,services,course,other,1.00,2.00,1.00,no,no,no,no,no,-6.00,yes,yes,no,4.00,5.00,NaN,4.00,3.00,NaN
314,GP,F,19,U,GT3,T,1.00,1.00,at_home,health,home,other,1.00,NaN,2.00,no,no,no,no,no,NaN,yes,yes,yes,4.00,NaN,2.00,3.00,14.00,65.00
315,GP,F,19,R,GT3,T,2.00,3.00,other,other,reputation,other,1.00,3.00,1.00,no,no,no,no,yes,-9.00,yes,yes,yes,4.00,1.00,2.00,3.00,40.00,55.00
340,GP,F,19,U,GT3,T,2.00,1.00,services,services,home,other,1.00,3.00,1.00,no,no,yes,yes,NaN,-9.00,yes,NaN,yes,4.00,3.00,4.00,3.00,4.00,55.00
350,MS,M,19,NaN,GT3,T,1.00,1.00,other,services,home,other,3.00,2.00,3.00,no,no,no,no,NaN,-6.00,yes,yes,no,5.00,4.00,4.00,2.00,8.00,NaN
353,MS,M,19,R,GT3,T,1.00,1.00,other,other,home,other,3.00,1.00,1.00,no,yes,no,no,yes,-3.00,yes,yes,no,4.00,4.00,4.00,5.00,4.00,40.00
370,MS,F,19,U,LE3,T,3.00,2.00,services,services,home,other,2.00,2.00,2.00,no,no,no,yes,yes,-6.00,yes,no,yes,3.00,2.00,2.00,3.00,4.00,45.00

In [30]:
# Строки для учеников с одновременной семейной и дополнительной 
# образовательной поддержкой, но при этом не посещающих
# дополнительные внеучебные занятия и платные занятия по математике
print(f'Количество аномальных строк: {data[
    (data['famsup'] == 'yes') & (data['schoolsup'] == 'yes') &
    (data['activities'] == 'no') &
    (data['paid'] == 'no')
].shape[0]}')
data[
    (data['famsup'] == 'yes') & 
    (data['schoolsup'] == 'yes') & 
    (data['activities'] == 'no') & 
    (data['paid'] == 'no')
]

Количество аномальных строк: 6

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,"studytime, granular",higher,internet,romantic,famrel,freetime,goout,health,absences,score
7,GP,F,17,U,GT3,A,4.00,4.00,other,teacher,home,mother,2.00,2.00,0.00,yes,yes,no,no,yes,-6.00,yes,no,no,4.00,1.00,4.00,1.00,6.00,30.00
72,GP,F,15,R,GT3,T,1.00,1.00,other,other,reputation,mother,1.00,2.00,2.00,yes,yes,no,no,no,-6.00,yes,yes,yes,NaN,3.00,4.00,5.00,2.00,25.00
92,GP,F,16,NaN,LE3,T,NaN,1.00,other,other,home,father,1.00,2.00,0.00,yes,yes,no,no,yes,-6.00,yes,no,no,3.00,3.00,NaN,2.00,4.00,30.00
154,GP,F,17,U,GT3,T,4.00,4.00,other,teacher,course,mother,1.00,1.00,0.00,yes,yes,no,no,yes,-3.00,yes,no,yes,4.00,2.00,1.00,4.00,0.00,60.00
161,GP,M,15,R,GT3,T,3.00,NaN,other,NaN,course,mother,2.00,2.00,2.00,yes,yes,no,no,yes,-6.00,yes,yes,yes,4.00,4.00,4.00,3.00,6.00,35.00
251,GP,M,16,U,GT3,T,3.00,3.00,at_home,other,reputation,other,3.00,2.00,0.00,yes,yes,no,no,no,-6.00,yes,NaN,no,5.00,3.00,3.00,2.00,6.00,50.00

In [ ]:
! создать списо строк для удаления

In [15]:
# Получение описательных статистик для определения 
# количеств уникальных значений у номинативных переменных
display(data.describe(include=['object']))

,school,sex,address,famsize,Pstatus,Mjob,Fjob,reason,guardian,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic
count,395,395,378,368,350,376,359,378,364,386,356,355,381,379,375,361,364
unique,2,2,2,2,2,5,5,4,3,2,2,2,2,2,2,2,2
top,GP,F,U,GT3,T,other,other,course,mother,no,yes,no,yes,yes,yes,yes,no
freq,349,208,295,261,314,133,197,137,250,335,219,200,195,300,356,305,240

<ВАШИ ВЫВОДЫ>

## Часть 2. Исследование отдельных признаков

Теперь, познакомившись с датасетом, можно приступать к устранению тех проблемных элементов в признаках, которые вы могли обнаружить в ходе первой части. В процессе можете продемонстрировать более детальный анализ отдельных признаков, возможно, найдете еще что-нибудь интересное.

**Рекомендуем обратить внимание на следующие моменты:**
- Нужно ли удалять из датасета учеников с нулевыми баллами в признаке `score`?
- Есть ли выбросы в признаках согласно статистическим методам (например, по межквартильному размаху)?
- Что могут означать пропуски в тех или иных признаках, какую стратегию их обработки вы бы предложили?

В остальном представьте более детальный анализ — не менее 10-ти различных признаков в датасете. Напишите везде текстовые выводы, постарайтесь интерпретировать результаты, про найденные интересные моменты в данных можете рассказать на устной защите проекта.

Постарайтесь оформить и представить мини-исследование, ограничений по количеству гипотез и проверок нет: можете создать ниже сколько требуется текстовых и кодовых ячеек, главное — наглядно продемонстрировать ответы на все вопросы.

**Рекомендации по оформлению кода:**
- повторяющийся код оборачивайте в функции;
- соблюдайте правила PEP-8.

In [16]:
# Ваш код

<ВАШИ ВЫВОДЫ>

In [17]:
# Ваш код

<ВАШИ ВЫВОДЫ>

In [18]:
# Ваш код

<ВАШИ ВЫВОДЫ>

## Часть 3. Корреляционный анализ
Проведите корреляционный анализ числовых признаков. Это исследование позволит ответить на вопрос о парных зависимостях в данных.

Целевой признак, на основе которого в дальнейшем будет строиться ML-модель — это столбец `score`. Обратите внимание на связи остальных признаков с ним, а также на взаимные связи между обычными признаками (не целевыми).

Постройте несколько визуализаций, можете подкрепить исследование статистическими гипотезами. В конце напишите подробный отчет по корреляционному анализу, постарайтесь интерпретировать результаты, то есть обоснуйте, насколько они логичны и чем могли быть вызваны.

По результатам исследования, возможно, некоторые признаки вы посчитаете неинформативными. Их вполне можно удалить.

In [19]:
# Ваш код

<ВАШИ ВЫВОДЫ>

In [20]:
# Ваш код

<ВАШИ ВЫВОДЫ>

In [21]:
# Ваш код

<ВАШИ ВЫВОДЫ>

## Часть 4. Анализ и очистка номинативных показателей
Как вы могли заметить, в данных довольно много нечисловых признаков. Они требуют отдельного детального анализа.

В первую очередь обратите внимание на пропуски, количество уникальных значений в каждом признаке, в также их корректность. При желании можете подкрепить анализ статистическими гипотезами. Неинформативные признаки или строки нужно удалить, в конце необходимо будет сформировать итоговый датасет для передачи на этап моделирования. Зафиксируйте и обоснуйте выполненные преобразования в текстовых ячейках.

In [22]:
# Ваш код

<ВАШИ ВЫВОДЫ>

In [23]:
# Ваш код

<ВАШИ ВЫВОДЫ>

In [24]:
# Ваш код

<ВАШИ ВЫВОДЫ>

## Часть 5. Итоги и выводы
Последняя, но самая важная часть проекта, — сделать итоговые выводы по проделанной работе. Опишите кратко, какие проблемы были обнаружены в данных, какие интересные моменты вы нашли и какие бы признаки рекомендовали в первую очередь для построения модели.

Также сохраните финальный очищенный датасет в файл.

In [25]:
# Ваш код сохранения файла

<ВАШИ ИТОГОВЫЕ ВЫВОДЫ>